# Generated by Django 5.2.8 on 2025-11-13 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('New', 'Новая'), ('In Progress', 'В процессе'), ('Completed', 'Выполнена'), ('On Hold', 'Приостановлена')], default='New', max_length=15, verbose_name='Статус')),
                ('priority', models.PositiveSmallIntegerField(choices=[('1', 'Низкий'), ('2', 'Средний'), ('3', 'Высокий'), ('4', 'Критический')], default=2, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_tracker.project', verbose_name='Проект')),
            ],
        ),
    ]
